- hosts: all
  user: "{{ project }}"
  vars:
    projectName: "{{ project }}"
    user: "{{ project }}"
    type: "{{ build_type }}"
    ansible_python_interpreter: "{{ tmp_dir }}/.venv/bin/python"
    
  tasks:
    - name: Set username
      ansible.builtin.set_fact:
        remote_user: "{{ user }}"
        shared_dir: /var/www/{{ projectName }}/ss/shared
        releases_dir: /var/www/{{ projectName }}/ss/releases
        tmp_dir: "{{releases_dir}}/{{ ansible.datetime.date}}"
        curr_dir: /var/www/{{ projectName }}/ss/current
        
    - name: Copy project source files
      ansible.builtin.synchronize:
        src: ./
        dest: "{{ tmp_dir }}"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=deploy.yml"
          
    - name: Make symlink for .secrets.toml
      ansible.builtin.file:
        src: "{{ shared_dir }}/config/.secrets.toml"
        dest: "{{ temp_dir }}/.secrets.toml"
        state: link
        force: yes
        
    - name: Make symlink for gunicorn_config
      ansible.builtin.file:
        src: "{{ shared_dir }}/config/gunicorn_config.py"
        dest: "{{ tmp_dir }}/gunicorn_config.py"
        state: link
        force: yes
        
    - name: Make symlink for .venv
      ansible.builtin.file:
        src: "{{ shared_dir }}/.venv"
        dest: "{{ tmp_dir }}/.venv"
        state: link
        force: yes
        
    - name: Make symlink for logs
      ansible.builtin.file:
        src: "{{ shared_dir }}/logs"
        dest: "{{ tmp_dir }}/logs"
        state: link
        force: yes
        
    - name: Install dependencies with Poetry
      ansible.builtin.command: 
        argv:
          - /home/{{ projectName }}/.local/bin/poetry
          - install
          - --no-interaction
          - --without=dev
      args:
        chdir: "{{ tmp_dir }}"
      environment:
        PIP_CACHE_DIR: /tmp/pip-cache

    - name: Run DB migrations
      ansible.builtin.command:
        argv:
          - python
          - manage.py
          - migrate
      args:
      chdir: "{{ tmp_dir }}"
      
    - name: Update current release symlink
      ansible.builtin.file:
        path: "{{ curr_dir }}"
        src: "{{ tmp_dir }}"
        state: link
        force: yes
        
    - name: Restart gunicorn service
      ansible.builtin.service:
        name: gunicorn
        state: restarted
      
    - name: Restart Celery service
      ansisble.builtin.service:
        name: gunicorn
        state: restarted
      
    - name: Delete previous deployments
      ansible.builtin.block:
        - name: Get Current deployment path
          ansible.builtin.command: readlink -f {{ curr_dir }}
          register: current_deploy_path
          
        - name: Find all releases
          ansible.builtin.find:
            paths: "{{ releases_dir }}"
            file_type: directory
          register: old_releases
          
        - name: Remove old deployments
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ old_releases.files }}"
          when:
            - item.path != current_deploy_path.stdout