dynaconf_merge = true

#
# Default secrets
#

[default.postgres]
password = ""

[default.django]
secret_key = ""

[default.email]
host_user = ""
host_password = ""

#
# Dev secrets
#

[development.django]
secret_key = ""

#
# Production secrets
#

[production.django]
secret_key = ""