[postgres]
name = ""
user = ""
password = ""
host = ""
port = ""

[pagination]
media_items = 10

[django]
secret_key = ''
debug = true
allowed_hosts = ["localhost", "127.0.0.1"]
cookies_secure = false

[logging]
logging_enabled = true
log_level = "INFO"
django_log_level = "INFO"
db_log_level = "DEBUG"

[email]
host = 'localhost'
port = 8025
use_tls = false
host_user = ''
host_password = ''
default_from_email = 'from@backlog.co'

[celery]
broker_url = "redis://localhost:6379/0"
result_backend = "redis://localhost:6379/1"