[postgres]
name = ""
user = ""
password = ""
host = ""
port = ""

[pagination]
media_items = 10

[django]
secret_key = ''
debug = true
allowed_hosts = ["localhost", "127.0.0.1"]
cookies_secure = false