---
- name: Create gunicorn service file from template
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn-{{ project_name }}.service
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root

- name: Flush handlers so systemd knows about new service
  ansible.builtin.meta: flush_handlers

- name: Start and enable gunicorn service
  ansible.builtin.systemd:
    name: "gunicorn-{{ project_name }}"
    state: started
    enabled: true
