# Generated by Django 6.0.3 on 2026-03-22 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('WAN', 'Want'), ('PRG', 'In Progress'), ('CMP', 'Completed'), ('DRP', 'Dropped')], default='WAN', max_length=16)),
                ('rating', models.FloatField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=(0.0, '0.0'), null=True)),
                ('media_type', models.CharField(choices=[('GAM', 'Game'), ('BOK', 'Book'), ('MUS', 'Music'), ('MOV', 'Movie')])),
                ('priority', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('notes', models.TextField(max_length=512, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('metadata', models.JSONField()),
                ('external_id', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'media_item',
                'verbose_name_plural': 'media_items',
                'db_table': 'media_item',
            },
        ),
    ]
