# Generated by Django 5.2.12 on 2026-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='notes',
            field=models.TextField(blank=True, default=None, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.FloatField(blank=True, choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(blank=True, choices=[('want', 'Want'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='want', max_length=16),
        ),
    ]
